<x-ratings.shell>
    <div class="min-h-screen bg-[#F8FAFC] px-4 py-10" x-data="{ score: {{ old('score', 0) }}, commentOpen: {{ old('comment') ? 'true' : 'false' }} }">
        <div class="mx-auto max-w-xl"><a href="{{ url()->previous() }}" class="text-sm font-medium text-slate-500">← Back</a><div class="mt-7"><h1 class="text-2xl font-bold text-slate-900">Rate {{ ucfirst($reviewee->role) }}</h1><p class="mt-1 text-sm text-slate-400">Share your experience to help the community.</p></div>
            <form method="POST" action="{{ route('ratings.store',$booking) }}" class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">@csrf
                <div class="flex items-center gap-4 rounded-xl bg-slate-50 p-4"><div class="flex h-11 w-11 items-center justify-center rounded-full bg-green-600 text-sm font-bold text-white">{{ strtoupper(substr($reviewee->name,0,2)) }}</div><div><div class="font-semibold">{{ $reviewee->name }}</div><div class="text-xs text-slate-400">{{ ucfirst($reviewee->role) }} · {{ $booking->trip->completed_at->format('j M Y') }}</div></div></div>
                <fieldset class="mt-7 text-center"><legend class="w-full text-sm font-semibold text-slate-700">How was your {{ $reviewee->role === 'driver' ? 'ride' : 'passenger' }}?</legend><div class="mt-3 flex justify-center gap-2">@for($i=1;$i<=5;$i++)<button type="button" @click="score={{$i}}" class="text-5xl leading-none transition hover:scale-110" :class="score >= {{$i}} ? 'text-amber-400' : 'text-slate-200'" aria-label="{{$i}} stars">★</button>@endfor</div><input type="hidden" name="score" :value="score"><p class="mt-3 text-sm font-semibold text-green-600" x-text="['','Poor','Fair','Good','Very good','Excellent'][score]"></p>@error('score')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</fieldset>
                <div class="mt-6 border-t border-slate-100 pt-5"><button type="button" @click="commentOpen=!commentOpen" class="w-full rounded-xl border border-slate-200 py-2.5 text-sm font-semibold text-slate-600">Add Comments &amp; Feedback</button><div x-show="commentOpen" x-cloak class="mt-4"><label for="comment" class="text-sm font-semibold">Your Feedback <span class="font-normal text-slate-400">(optional)</span></label><textarea id="comment" name="comment" maxlength="300" rows="5" class="mt-2 w-full rounded-xl border-slate-300 text-sm focus:border-green-500 focus:ring-green-500" placeholder="Tell us about your experience...">{{ old('comment') }}</textarea>@error('comment')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div></div>
                <button class="mt-5 w-full rounded-xl bg-[#22C55E] py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40" :disabled="score===0">Submit Rating</button>
            </form>
        </div>
    </div>
</x-ratings.shell>
