<x-app-layout>
    @php $badge = ['Scheduled' => 'bg-blue-50 text-blue-700', 'In Progress' => 'bg-orange-50 text-orange-700', 'Completed' => 'bg-gray-100 text-gray-600', 'Cancelled' => 'bg-red-50 text-red-700']; @endphp
    <div class="min-h-screen bg-[#F8FAFC] px-4 py-8 sm:px-6 lg:px-8">
        <div class="mx-auto max-w-7xl">
            <x-trip-toast />
            <div class="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><h1 class="text-2xl font-bold text-gray-900">My Trips</h1><div class="flex flex-wrap gap-3"><a href="{{ route('driver.trips.journey') }}" class="rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">My Journey</a><a href="{{ route('driver.trips.history') }}" class="rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">Trip History</a><a href="{{ route('driver.trips.create') }}" class="rounded-xl bg-[#16A34A] px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-[#15803D]">＋ Create Trip</a></div></div>
            <div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                @foreach ([['Upcoming Trips', $stats['Scheduled'], 'text-blue-600', 'border-blue-100'], ['In Progress', $stats['In Progress'], 'text-orange-600', 'border-orange-100'], ['Completed Trips', $stats['Completed'], 'text-gray-600', 'border-gray-100'], ['Cancelled Trips', $stats['Cancelled'], 'text-red-600', 'border-red-100']] as [$label, $value, $color, $border])
                    <div class="rounded-2xl border {{ $border }} bg-white p-4"><p class="mb-1 text-xs font-medium text-gray-500">{{ $label }}</p><p class="text-3xl font-bold {{ $color }}">{{ $value }}</p></div>
                @endforeach
            </div>
            <form class="mb-6 flex flex-col gap-3 lg:flex-row" method="GET"><input name="search" value="{{ request('search') }}" placeholder="Search destination... Example: Shah Alam, Cyberjaya" class="min-w-0 flex-1 rounded-xl border-gray-200 bg-white px-4 py-2.5 text-sm focus:border-[#16A34A] focus:ring-[#16A34A]" /><select name="status" class="rounded-xl border-gray-200 bg-white text-sm text-gray-700 focus:border-[#16A34A] focus:ring-[#16A34A]"><option value="">All Status</option>@foreach(['Scheduled','In Progress'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><select name="sort" class="rounded-xl border-gray-200 bg-white text-sm text-gray-700 focus:border-[#16A34A] focus:ring-[#16A34A]"><option value="date">Sort by Date</option><option value="distance" @selected(request('sort') === 'distance')>Sort by Distance</option></select><button class="rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">Apply</button></form>
            @if($trips->isEmpty())
                <div class="rounded-2xl border border-gray-100 bg-white px-6 py-20 text-center"><div class="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#DCFCE7]"><x-icons.lucide name="car-front" class="h-9 w-9 text-[#16A34A]" /></div><p class="mt-4 text-base font-semibold text-gray-700">No active trips to display.</p><p class="mt-1 text-sm text-gray-400">Click “Create Trip” to create a new trip.</p></div>
            @else
                <div class="space-y-4">@foreach($trips as $trip)
                    <article class="rounded-2xl border border-gray-100 bg-white p-5 transition-shadow hover:shadow-md"><div class="flex gap-4"><div class="hidden h-20 w-28 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-[#DCFCE7] to-[#BBF7D0] sm:flex"><x-icons.lucide name="car-front" class="h-8 w-8 text-[#16A34A]" /></div><div class="min-w-0 flex-1"><div class="mb-2 flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><h2 class="flex min-w-0 items-center gap-2 truncate text-base font-semibold text-gray-900"><span class="truncate">{{ $trip->departure_location }}</span><x-icons.lucide name="arrow-right" class="h-3.5 w-3.5 shrink-0 text-gray-400" /><span class="truncate">{{ $trip->destination }}</span></h2><span class="inline-flex w-fit shrink-0 rounded-full px-2.5 py-1 text-xs font-medium {{ $badge[$trip->status] }}">{{ $trip->status }}</span></div><div class="mb-4 grid gap-x-6 gap-y-1.5 text-xs text-gray-600 sm:grid-cols-3"><span class="flex items-center gap-1.5"><x-icons.lucide name="calendar" class="h-3.5 w-3.5 text-gray-400" />{{ $trip->departure_at->format('d M Y') }}</span><span class="flex items-center gap-1.5"><x-icons.lucide name="clock" class="h-3.5 w-3.5 text-gray-400" />{{ $trip->departure_at->format('g:i A') }}</span><span class="flex items-center gap-1.5"><x-icons.lucide name="route" class="h-3.5 w-3.5 text-gray-400" />{{ $trip->estimated_distance_km ? $trip->estimated_distance_km.' km' : '—' }}</span><span class="flex items-center gap-1.5"><x-icons.lucide name="car-front" class="h-3.5 w-3.5 text-gray-400" />{{ $trip->vehicle->brand }} {{ $trip->vehicle->model }}</span><span class="font-mono text-gray-400">{{ $trip->vehicle->plate_number }}</span><span class="flex items-center gap-1.5"><x-icons.lucide name="users" class="h-3.5 w-3.5 text-gray-400" />0/{{ $trip->available_seats }} seats</span></div><div class="flex flex-wrap gap-2"><a href="{{ route('driver.trips.show', ['trip' => $trip, 'return_to' => 'driver.trips.index']) }}" class="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-gray-50 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-100"><x-icons.lucide name="eye" class="h-3.5 w-3.5" />View Details</a>@if($trip->status === 'Scheduled')<a href="{{ route('driver.trips.edit', ['trip' => $trip, 'return_to' => 'driver.trips.index']) }}" class="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-gray-50 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-100"><x-icons.lucide name="pencil" class="h-3.5 w-3.5" />Edit</a><x-trip-confirmation name="cancel-{{ $trip->trip_id }}" title="Cancel Trip?" message="Passengers with confirmed bookings will be notified. This action cannot be undone." confirm-label="Confirm Cancel" :action="route('driver.trips.cancel', $trip)" variant="danger" class="rounded-lg px-3 py-1.5 text-xs font-medium">Cancel</x-trip-confirmation>@endif</div></div></div></article>
                @endforeach</div><div class="mt-6">{{ $trips->links() }}</div>
            @endif
        </div>
    </div>
</x-app-layout>
