<x-app-layout>
    @php
        $badge = ['Scheduled' => 'bg-blue-50 text-blue-700', 'In Progress' => 'bg-orange-50 text-orange-700'];
        $inProgress = $trips->where('status', 'In Progress');
        $scheduled = $trips->where('status', 'Scheduled');
        $hasInProgressTrip = $inProgress->isNotEmpty();
    @endphp
    <div class="min-h-screen bg-[#F8FAFC] p-8"><div class="mx-auto max-w-7xl">
        <div class="mb-8 flex items-center gap-3"><a href="{{ route('driver.trips.index') }}" class="rounded-xl p-2 text-gray-400 hover:bg-gray-100"><x-icons.lucide name="arrow-left" class="h-[18px] w-[18px]" /></a><h1 class="text-2xl font-bold text-gray-900">My Journey</h1></div>
        <x-trip-toast />
        @if($trips->isEmpty())
            <div class="flex flex-col items-center justify-center rounded-2xl border border-gray-100 bg-white py-20"><div class="flex h-20 w-20 items-center justify-center rounded-full bg-[#DCFCE7]"><x-icons.lucide name="car-front" class="h-9 w-9 text-[#16A34A]" /></div><p class="mt-4 text-base font-semibold text-gray-700">No scheduled or ongoing trips.</p><a href="{{ route('driver.trips.index') }}" class="mt-4 inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700"><x-icons.lucide name="arrow-left" class="h-3.5 w-3.5" />Back to My Trips</a></div>
        @else
            <div class="space-y-8">
                @if($inProgress->isNotEmpty())
                    <section><h2 class="mb-4 flex items-center gap-2 text-base font-semibold text-gray-900"><span class="h-2 w-2 animate-pulse rounded-full bg-orange-500"></span>In Progress</h2><div class="space-y-3">@foreach($inProgress as $trip)<article class="rounded-2xl border border-orange-100 bg-white p-5"><div class="mb-4 flex items-center justify-between"><h3 class="flex items-center gap-2 text-base font-semibold text-gray-900"><span>{{ $trip->departure_location }}</span><x-icons.lucide name="arrow-right" class="h-3.5 w-3.5 text-gray-400" /><span>{{ $trip->destination }}</span></h3><span class="rounded-full px-2.5 py-1 text-xs font-medium {{ $badge['In Progress'] }}">In Progress</span></div><div class="flex gap-2"><x-trip-confirmation name="complete-{{ $trip->trip_id }}" title="Complete Journey?" message="This will notify passengers and mark this trip as completed." confirm-label="Confirm Complete" :action="route('driver.trips.complete', $trip)" class="flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium"><x-icons.lucide name="circle-check" class="h-3.5 w-3.5" />Complete Trip</x-trip-confirmation><a href="{{ route('driver.trips.show', ['trip' => $trip, 'return_to' => 'driver.trips.journey']) }}" class="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700"><x-icons.lucide name="eye" class="h-3.5 w-3.5" />View Details</a></div></article>@endforeach</div></section>
                @endif
                @if($scheduled->isNotEmpty())
                    <section><h2 class="mb-4 text-base font-semibold text-gray-900">Scheduled Trips</h2><div class="space-y-3">@foreach($scheduled as $trip)<article class="rounded-2xl border border-gray-100 bg-white p-5"><div class="mb-3 flex items-start justify-between"><div><h3 class="flex items-center gap-2 text-base font-semibold text-gray-900"><span>{{ $trip->departure_location }}</span><x-icons.lucide name="arrow-right" class="h-3.5 w-3.5 text-gray-400" /><span>{{ $trip->destination }}</span></h3><p class="mt-1 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-gray-500"><span class="flex items-center gap-1"><x-icons.lucide name="calendar" class="h-3 w-3" />{{ $trip->departure_at->format('d M Y') }}</span><span class="flex items-center gap-1"><x-icons.lucide name="clock" class="h-3 w-3" />{{ $trip->departure_at->format('g:i A') }}</span><span class="flex items-center gap-1"><x-icons.lucide name="users" class="h-3 w-3" />0/{{ $trip->available_seats }} passengers</span></p></div><span class="rounded-full px-2.5 py-1 text-xs font-medium {{ $badge['Scheduled'] }}">Scheduled</span></div><p class="mb-3 flex items-center gap-1.5 text-xs text-gray-400"><x-icons.lucide name="car-front" class="h-3.5 w-3.5" />{{ $trip->vehicle->brand }} {{ $trip->vehicle->model }} - {{ $trip->vehicle->plate_number }}</p><div class="flex gap-2"><x-trip-confirmation name="start-{{ $trip->trip_id }}" title="Start Journey?" message="Passengers will receive a notification that your journey has started." confirm-label="Start Journey" :action="route('driver.trips.start', $trip)" :disabled="$hasInProgressTrip" disabled-message="Please complete the current trip before starting another trip." class="inline-flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium"><x-icons.lucide name="play" class="h-3.5 w-3.5" />Start Trip</x-trip-confirmation><a href="{{ route('driver.trips.show', ['trip' => $trip, 'return_to' => 'driver.trips.journey']) }}" class="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700"><x-icons.lucide name="eye" class="h-3.5 w-3.5" />View Details</a></div></article>@endforeach</div></section>
                @endif
            </div>
        @endif
    </div></div>
</x-app-layout>
