<x-app-layout>
    <style>[x-cloak] { display: none !important; }</style>

    <div class="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8" x-data="{
        currentView: '{{ $errors->updatePassword->isNotEmpty() || $errors->userDeletion->isNotEmpty() ? 'security' : 'profile' }}',
        editingProfile: {{ $errors->isNotEmpty() && ! $errors->updatePassword->isNotEmpty() && ! $errors->userDeletion->isNotEmpty() ? 'true' : 'false' }},
        showLogoutModal: false, showDeleteModal: {{ $errors->userDeletion->isNotEmpty() ? 'true' : 'false' }}, showDisconnectGoogleModal: false,
        showCurrentPassword: false, showNewPassword: false, showConfirmPassword: false, newPassword: '',
        get passwordScore() { let score = 0; if (this.newPassword.length >= 8) score++; if (/[a-z]/.test(this.newPassword) && /[A-Z]/.test(this.newPassword)) score++; if (/\d/.test(this.newPassword)) score++; if (/[^A-Za-z0-9]/.test(this.newPassword)) score++; return score; },
        get passwordLabel() { return ['Very weak', 'Weak', 'Medium', 'Strong', 'Very strong'][this.passwordScore]; },
        get passwordWidth() { return (this.passwordScore * 25) + '%'; },
        get passwordColor() { return ['bg-red-500', 'bg-red-500', 'bg-amber-400', 'bg-green-500', 'bg-green-600'][this.passwordScore]; }
    }">
        <div class="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
            <div><p class="text-sm font-semibold text-[#2E7D32]">Driver account</p><h2 class="mt-1 text-3xl font-bold tracking-tight text-gray-950">My Profile</h2><p class="mt-2 text-sm text-gray-600">Manage your account, vehicles, and driving preferences.</p></div>
            <a href="{{ route('driver.vehicles.create') }}" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#2E7D32] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#256b29]"><x-icons.lucide name="plus" class="h-4 w-4" />Add Vehicle</a>
        </div>

        <div class="mb-6"><x-profile-completeness-card :profile-completeness="$profileCompleteness" /></div>

        <div class="mb-6 flex gap-1 overflow-x-auto rounded-xl border border-gray-200 bg-white p-1.5" role="tablist" aria-label="Driver profile sections">
            @foreach ([['profile', 'Personal Info', 'user-round'], ['vehicles', 'My Vehicles', 'car-front'], ['preferences', 'Preferences', 'sliders-horizontal'], ['security', 'Security', 'shield-check']] as [$view, $label, $icon])
                <button type="button" @click="currentView = '{{ $view }}'" :class="currentView === '{{ $view }}' ? 'bg-green-50 text-[#2E7D32]' : 'text-gray-500 hover:bg-gray-50 hover:text-gray-800'" class="inline-flex min-h-10 shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold transition" role="tab" :aria-selected="currentView === '{{ $view }}'"><x-icons.lucide :name="$icon" class="h-4 w-4" />{{ $label }}</button>
            @endforeach
        </div>

        <div x-show="currentView === 'profile'" x-transition.opacity>
            <section class="overflow-hidden rounded-2xl border border-gray-200 bg-white">
                <div class="flex flex-col gap-5 border-b border-gray-100 p-6 sm:flex-row sm:items-center sm:justify-between">
                    <div class="flex min-w-0 items-center gap-4">
                        @if ($user->photo)<img src="{{ asset('storage/'.$user->photo) }}" alt="Profile photo for {{ $user->name }}" class="h-20 w-20 rounded-full border border-gray-200 object-cover">@else<span class="flex h-20 w-20 shrink-0 items-center justify-center rounded-full bg-[#2E7D32] text-2xl font-bold text-white">{{ mb_strtoupper(mb_substr($user->name, 0, 1)) }}</span>@endif
                        <div class="min-w-0"><h3 class="truncate text-xl font-bold text-gray-950">{{ $user->name }}</h3><p class="mt-1 truncate text-sm text-gray-500">{{ $user->email }}</p><div class="mt-3 flex flex-wrap items-center gap-2"><span class="rounded-full bg-green-100 px-2.5 py-1 text-xs font-semibold text-[#2E7D32]">Driver</span><a href="{{ route('ratings.received', $user) }}" class="inline-flex items-center gap-1 text-xs font-semibold text-amber-600 hover:text-amber-700"><x-icons.lucide name="star" class="h-3.5 w-3.5 fill-current" />{{ $user->ratings_received_count ? number_format((float) $user->ratings_received_avg_score, 1) : 'No ratings' }}<span class="font-normal text-gray-400">({{ $user->ratings_received_count }} {{ Str::plural('review', $user->ratings_received_count) }})</span></a></div></div>
                    </div>
                    <button type="button" @click="editingProfile = ! editingProfile" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50"><x-icons.lucide name="pencil" class="h-4 w-4" /><span x-text="editingProfile ? 'Cancel' : 'Edit Profile'"></span></button>
                </div>
                <div class="grid divide-y divide-gray-100 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div class="p-5"><p class="text-xs font-medium uppercase tracking-wide text-gray-400">Name</p><p class="mt-2 text-sm font-semibold text-gray-900">{{ $user->name }}</p></div><div class="p-5"><p class="text-xs font-medium uppercase tracking-wide text-gray-400">Email Address</p><p class="mt-2 truncate text-sm font-semibold text-gray-900">{{ $user->email }}</p></div><div class="p-5"><p class="text-xs font-medium uppercase tracking-wide text-gray-400">Account Type</p><p class="mt-2 text-sm font-semibold text-gray-900">{{ $user->usesGoogleAuthentication() ? 'Google account' : 'Password account' }}</p></div></div>
            </section>
            <section x-cloak x-show="editingProfile" x-transition.opacity class="mt-6 rounded-2xl border border-gray-200 bg-white p-6"><h3 class="text-lg font-bold text-gray-950">Edit Personal Information</h3><p class="mt-1 text-sm text-gray-600">Your email address and role are locked for account security.</p><form method="POST" action="{{ route('driver.profile.update') }}" enctype="multipart/form-data" class="mt-6 space-y-5" x-data="{ preview: null }">@csrf @method('PATCH')
                <div class="flex flex-col gap-4 sm:flex-row sm:items-center"><div class="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-full bg-green-100 text-[#2E7D32]"><template x-if="preview"><img :src="preview" alt="Profile photo preview" class="h-full w-full object-cover"></template><template x-if="!preview">@if ($user->photo)<img src="{{ asset('storage/'.$user->photo) }}" alt="Profile photo for {{ $user->name }}" class="h-full w-full object-cover">@else<span class="text-xl font-bold">{{ mb_strtoupper(mb_substr($user->name, 0, 1)) }}</span>@endif</template></div><label class="inline-flex w-fit cursor-pointer items-center gap-2 rounded-lg border border-gray-300 px-3 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50"><x-icons.lucide name="image-up" class="h-4 w-4" />Change Photo<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" class="sr-only" @change="const file = $event.target.files[0]; if (file) preview = URL.createObjectURL(file)"></label></div>
                @error('photo')<p class="text-sm text-red-600">{{ $message }}</p>@enderror
                <div class="grid gap-5 sm:grid-cols-2"><div><label for="driver_name" class="mb-1.5 block text-sm font-semibold text-gray-700">Name</label><input id="driver_name" name="name" type="text" value="{{ old('name', $user->name) }}" required autocomplete="name" class="block w-full rounded-lg border-gray-300 text-sm shadow-sm focus:border-[#2E7D32] focus:ring-[#2E7D32]"><x-input-error :messages="$errors->get('name')" class="mt-2" /></div><div><label for="driver_email" class="mb-1.5 block text-sm font-semibold text-gray-700">Email Address</label><input id="driver_email" type="email" value="{{ $user->email }}" readonly disabled class="block w-full cursor-not-allowed rounded-lg border-gray-200 bg-gray-50 text-sm text-gray-500"><p class="mt-1.5 text-xs text-gray-400">Email address cannot be changed.</p></div></div>
                <div class="flex justify-end gap-3"><button type="button" @click="editingProfile = false" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">Cancel</button><button type="submit" class="rounded-lg bg-[#2E7D32] px-4 py-2 text-sm font-semibold text-white hover:bg-[#256b29]">Save Changes</button></div>
            </form></section>
            <div class="mt-6"><x-phone-verification-card :user="$user" /></div>
            <div class="mt-6"><x-emergency-contacts-card :user="$user" /></div>
            <section class="mt-8">
                <h3 class="mb-3 text-base font-bold text-gray-900">Account</h3>
                <div class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
                    <button type="button" @click="currentView = 'security'; $nextTick(() => window.scrollTo({ top: 0, behavior: 'smooth' }))" class="group flex w-full items-center justify-between border-b border-gray-100 px-6 py-4 text-left transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#2E7D32]">
                        <span class="flex items-center gap-4">
                            <x-icons.lucide name="lock-keyhole" class="h-5 w-5 text-gray-400" />
                            <span><span class="block text-sm font-semibold text-gray-900">Change Password</span><span class="mt-0.5 block text-xs text-gray-400">Update your account password</span></span>
                        </span>
                        <x-icons.lucide name="chevron-right" class="h-5 w-5 text-gray-300 group-hover:text-gray-500" />
                    </button>
                    <button type="button" @click="currentView = 'security'; $nextTick(() => window.scrollTo({ top: 0, behavior: 'smooth' }))" class="group flex w-full items-center justify-between border-b border-gray-100 px-6 py-4 text-left transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#2E7D32]">
                        <span class="flex items-center gap-4">
                            <x-icons.lucide name="shield-check" class="h-5 w-5 text-gray-400" />
                            <span><span class="block text-sm font-semibold text-gray-900">Account Settings</span><span class="mt-0.5 block text-xs text-gray-400">Manage account data</span></span>
                        </span>
                        <x-icons.lucide name="chevron-right" class="h-5 w-5 text-gray-300 group-hover:text-gray-500" />
                    </button>
                    <button type="button" @click="showLogoutModal = true" class="group flex w-full items-center justify-between px-6 py-4 text-left transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#2E7D32]">
                        <span class="flex items-center gap-4"><x-icons.lucide name="log-out" class="h-5 w-5 text-gray-400" /><span class="text-sm font-semibold text-gray-900">Log Out</span></span>
                        <x-icons.lucide name="chevron-right" class="h-5 w-5 text-gray-300 group-hover:text-gray-500" />
                    </button>
                </div>
            </section>
        </div>

        <div x-cloak x-show="currentView === 'vehicles'" x-transition.opacity><section class="rounded-2xl border border-gray-200 bg-white p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h3 class="text-xl font-bold text-gray-950">My Vehicles</h3><p class="mt-1 text-sm text-gray-600">Vehicles are available for trip management once verified and active.</p></div><a href="{{ route('driver.vehicles.create') }}" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-[#2E7D32] px-4 py-2 text-sm font-semibold text-white hover:bg-[#256b29]"><x-icons.lucide name="plus" class="h-4 w-4" />Add Vehicle</a></div>
            @forelse ($vehicles as $vehicle)<article class="mt-5 flex flex-col gap-4 rounded-xl border border-gray-200 p-4 sm:flex-row sm:items-center"><div class="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-gray-100 text-gray-400">@if ($vehicle->vehicle_image_path)<img src="{{ asset('storage/'.$vehicle->vehicle_image_path) }}" alt="{{ $vehicle->brand }} {{ $vehicle->model }}" class="h-full w-full object-cover">@else<x-icons.lucide name="car-front" class="h-8 w-8" />@endif</div><div class="min-w-0 flex-1"><h4 class="truncate text-base font-bold text-gray-950">{{ $vehicle->brand }} {{ $vehicle->model }}</h4><p class="mt-1 font-mono text-sm text-gray-500">{{ $vehicle->plate_number }}</p><p class="mt-1 text-xs text-gray-500">{{ $vehicle->colour }} · {{ $vehicle->seat_capacity }} {{ Str::plural('seat', $vehicle->seat_capacity) }}</p></div><div class="flex flex-wrap items-center gap-2"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $vehicle->status === 'Active' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600' }}">{{ $vehicle->status }}</span><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $vehicle->verification_status === 'Verified' ? 'bg-green-100 text-green-700' : ($vehicle->verification_status === 'Rejected' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700') }}">{{ $vehicle->verification_status }}</span><a href="{{ route('driver.vehicles.show', $vehicle) }}" class="rounded-lg border border-gray-300 px-3 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">Manage</a></div></article>
            @empty<div class="mt-6 rounded-xl border border-dashed border-gray-300 px-6 py-12 text-center"><span class="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-gray-100 text-gray-400"><x-icons.lucide name="car-front" class="h-6 w-6" /></span><h4 class="mt-4 font-bold text-gray-900">No vehicles registered</h4><p class="mt-2 text-sm text-gray-500">Add and verify a vehicle before creating a trip.</p></div>@endforelse
            <a href="{{ route('driver.vehicles.index') }}" class="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#2E7D32] hover:text-[#256b29]">Open full vehicle management <x-icons.lucide name="arrow-right" class="h-4 w-4" /></a>
        </section></div>

        <div x-cloak x-show="currentView === 'preferences'" x-transition.opacity><section class="rounded-2xl border border-gray-200 bg-white p-6"><h3 class="text-xl font-bold text-gray-950">Driving Preferences</h3><p class="mt-1 text-sm text-gray-600">These preferences help passengers understand your ride environment.</p><form method="POST" action="{{ route('driver.profile.preferences.update') }}" class="mt-6 space-y-5">@csrf @method('PUT')
            <label class="flex cursor-pointer items-center justify-between gap-6 rounded-xl border border-gray-200 p-4 hover:border-green-200"><span><span class="block text-sm font-semibold text-gray-900">Smoking allowed</span><span class="mt-1 block text-sm text-gray-500">Passengers may smoke during the trip.</span></span><span class="relative inline-flex h-6 w-11 shrink-0 items-center"><input type="hidden" name="smoking_allowed" value="0"><input type="checkbox" name="smoking_allowed" value="1" class="peer sr-only" @checked(old('smoking_allowed', $preference->smoking_allowed))><span class="h-6 w-11 rounded-full bg-gray-200 transition peer-checked:bg-[#2E7D32]"></span><span class="absolute left-1 h-4 w-4 rounded-full bg-white transition peer-checked:translate-x-5"></span></span></label>
            <label class="flex cursor-pointer items-center justify-between gap-6 rounded-xl border border-gray-200 p-4 hover:border-green-200"><span><span class="block text-sm font-semibold text-gray-900">Pets allowed</span><span class="mt-1 block text-sm text-gray-500">Passengers may bring a pet with prior coordination.</span></span><span class="relative inline-flex h-6 w-11 shrink-0 items-center"><input type="hidden" name="pets_allowed" value="0"><input type="checkbox" name="pets_allowed" value="1" class="peer sr-only" @checked(old('pets_allowed', $preference->pets_allowed))><span class="h-6 w-11 rounded-full bg-gray-200 transition peer-checked:bg-[#2E7D32]"></span><span class="absolute left-1 h-4 w-4 rounded-full bg-white transition peer-checked:translate-x-5"></span></span></label>
            <div><label for="conversation_preference" class="mb-1.5 block text-sm font-semibold text-gray-900">Conversation preference</label><p class="mb-2 text-sm text-gray-500">Set the atmosphere you prefer while driving.</p><select id="conversation_preference" name="conversation_preference" class="block w-full rounded-lg border-gray-300 text-sm shadow-sm focus:border-[#2E7D32] focus:ring-[#2E7D32]">@foreach (['Quiet', 'Moderate', 'Chatty'] as $option)<option value="{{ $option }}" @selected(old('conversation_preference', $preference->conversation_preference) === $option)>{{ $option }}</option>@endforeach</select><x-input-error :messages="$errors->get('conversation_preference')" class="mt-2" /></div><div class="flex justify-end"><button type="submit" class="rounded-lg bg-[#2E7D32] px-4 py-2 text-sm font-semibold text-white hover:bg-[#256b29]">Save Preferences</button></div>
        </form></section></div>

        <div x-cloak x-show="currentView === 'security'" x-transition.opacity class="space-y-6">
            @if ($canManagePassword)<section class="rounded-2xl border border-gray-200 bg-white p-6"><h3 class="text-xl font-bold text-gray-950">Change Password</h3><p class="mt-1 text-sm text-gray-600">Use a strong, unique password to keep your account secure.</p><form method="POST" action="{{ route('password.update') }}" class="mt-6 max-w-xl space-y-5">@csrf @method('PUT')
                <div><label for="current_password" class="mb-1.5 block text-sm font-semibold text-gray-700">Current Password</label><div class="relative"><input id="current_password" name="current_password" :type="showCurrentPassword ? 'text' : 'password'" required autocomplete="current-password" class="block w-full rounded-lg border-gray-300 pr-12 text-sm shadow-sm focus:border-[#2E7D32] focus:ring-[#2E7D32]"><button type="button" @click="showCurrentPassword = !showCurrentPassword" class="absolute inset-y-0 right-0 px-3 text-gray-400 hover:text-gray-700" :aria-label="showCurrentPassword ? 'Hide current password' : 'Show current password'"><x-icons.lucide name="eye" class="h-5 w-5" /></button></div><x-input-error :messages="$errors->updatePassword->get('current_password')" class="mt-2" /></div>
                <div><label for="new_password" class="mb-1.5 block text-sm font-semibold text-gray-700">New Password</label><div class="relative"><input id="new_password" name="password" x-model="newPassword" :type="showNewPassword ? 'text' : 'password'" required autocomplete="new-password" class="block w-full rounded-lg border-gray-300 pr-12 text-sm shadow-sm focus:border-[#2E7D32] focus:ring-[#2E7D32]"><button type="button" @click="showNewPassword = !showNewPassword" class="absolute inset-y-0 right-0 px-3 text-gray-400 hover:text-gray-700" :aria-label="showNewPassword ? 'Hide new password' : 'Show new password'"><x-icons.lucide name="eye" class="h-5 w-5" /></button></div><div class="mt-3" x-show="newPassword.length" x-cloak><div class="flex justify-between text-xs"><span class="text-gray-500">Password strength</span><span x-text="passwordLabel" :class="passwordScore >= 3 ? 'text-green-700' : 'text-amber-600'" class="font-semibold"></span></div><div class="mt-1.5 h-2 overflow-hidden rounded-full bg-gray-100"><div class="h-full rounded-full transition-all" :class="passwordColor" :style="{ width: passwordWidth }"></div></div><p class="mt-2 text-xs text-gray-500">Use 8+ characters with uppercase, lowercase, a number, and a symbol.</p></div><x-input-error :messages="$errors->updatePassword->get('password')" class="mt-2" /></div>
                <div><label for="password_confirmation" class="mb-1.5 block text-sm font-semibold text-gray-700">Confirm New Password</label><div class="relative"><input id="password_confirmation" name="password_confirmation" :type="showConfirmPassword ? 'text' : 'password'" required autocomplete="new-password" class="block w-full rounded-lg border-gray-300 pr-12 text-sm shadow-sm focus:border-[#2E7D32] focus:ring-[#2E7D32]"><button type="button" @click="showConfirmPassword = !showConfirmPassword" class="absolute inset-y-0 right-0 px-3 text-gray-400 hover:text-gray-700" :aria-label="showConfirmPassword ? 'Hide confirmation password' : 'Show confirmation password'"><x-icons.lucide name="eye" class="h-5 w-5" /></button></div></div><div class="flex justify-end"><button type="submit" class="rounded-lg bg-[#2E7D32] px-4 py-2 text-sm font-semibold text-white hover:bg-[#256b29]">Update Password</button></div>
            </form></section>
            @else<section class="rounded-2xl border border-blue-200 bg-blue-50 p-6"><div class="flex gap-4"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-white text-blue-600"><x-icons.lucide name="shield-check" class="h-5 w-5" /></span><div><h3 class="text-lg font-bold text-blue-950">Google Account Security</h3><p class="mt-1 text-sm leading-6 text-blue-800">Your password is managed by Google. Update it in your Google Account security settings.</p></div></div></section>@endif
            <x-linked-accounts.google-card :user="$user" />
            <section class="rounded-2xl border border-gray-200 bg-white p-6"><div class="flex items-start gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-green-50 text-[#2E7D32]"><x-icons.lucide name="shield-check" class="h-5 w-5" /></span><div><h3 class="text-xl font-bold text-gray-950">Recent Login Activity</h3><p class="mt-1 text-sm text-gray-600">Review the latest devices that accessed your account.</p></div></div>@forelse ($recentLogins as $login)<div class="mt-5 flex items-center gap-4 border-t border-gray-100 pt-4 first:border-t-0 first:pt-0"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-gray-100 text-gray-500"><x-icons.lucide :name="str_starts_with($login->user_agent, 'Mozilla/5.0 (iPhone') || str_contains($login->user_agent, 'Android') ? 'smartphone' : 'monitor'" class="h-5 w-5" /></span><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold text-gray-900">{{ \App\Support\UserAgentParser::describe($login->user_agent) }}</p><p class="mt-1 text-xs text-gray-500">{{ $login->ip_address }} · {{ $login->login_at->format('M d, Y - H:i') }}</p></div></div>@empty<div class="mt-5 rounded-xl border border-dashed border-gray-300 bg-gray-50 px-4 py-6 text-center"><p class="text-sm font-semibold text-gray-700">No login activity yet</p><p class="mt-1 text-xs text-gray-500">Your successful sign-ins will appear here.</p></div>@endforelse</section>
            <section class="rounded-2xl border border-gray-200 bg-white p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="text-xl font-bold text-gray-950">Log Out</h3><p class="mt-1 text-sm text-gray-600">Sign out securely from this device.</p></div><button type="button" @click="showLogoutModal = true" class="inline-flex min-h-10 items-center justify-center rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">Log Out</button></div></section>
            <section class="rounded-2xl border border-red-200 bg-white p-6"><h3 class="text-xl font-bold text-red-700">Danger Zone</h3><p class="mt-1 text-sm text-gray-600">Deleting your account permanently removes your profile and associated data.</p><button type="button" @click="showDeleteModal = true" class="mt-5 rounded-lg border border-red-200 bg-white px-4 py-2 text-sm font-semibold text-red-600 hover:bg-red-50">Delete Account</button></section>
        </div>

        @if (session('status'))<div class="fixed bottom-6 right-6 z-40 rounded-xl bg-gray-900 px-4 py-3 text-sm font-semibold text-white shadow-lg" x-data="{ open: true }" x-show="open" x-transition role="status"><span>{{ match(session('status')) { 'profile-updated' => 'Profile updated successfully.', 'driver-preferences-updated' => 'Driving preferences saved successfully.', 'password-updated' => 'Password updated successfully.', 'google-account-linked' => 'Google account connected successfully.', 'google-account-unlinked' => 'Google account disconnected successfully.', default => 'Changes saved successfully.' } }}</span><button type="button" @click="open = false" class="ml-4 text-gray-300 hover:text-white" aria-label="Dismiss notification">×</button></div>@endif
        <div x-cloak x-show="showLogoutModal" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" x-transition.opacity><div @click.away="showLogoutModal = false" class="w-full max-w-sm rounded-2xl bg-white p-6 shadow-xl"><h3 class="text-lg font-bold text-gray-950">Log out?</h3><p class="mt-2 text-sm text-gray-600">Are you sure you want to log out of GreenPool?</p><div class="mt-6 flex gap-3"><button type="button" @click="showLogoutModal = false" class="flex-1 rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">Cancel</button><form method="POST" action="{{ route('logout') }}" class="flex-1">@csrf<button type="submit" class="w-full rounded-lg bg-[#2E7D32] px-4 py-2 text-sm font-semibold text-white hover:bg-[#256b29]">Log Out</button></form></div></div></div>
        <div x-cloak x-show="showDeleteModal" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" x-transition.opacity><div @click.away="showDeleteModal = false" class="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h3 class="text-lg font-bold text-gray-950">Delete your account?</h3><p class="mt-2 text-sm text-gray-600">This action cannot be undone. Enter your password to confirm.</p><form method="POST" action="{{ route('profile.destroy') }}" class="mt-5">@csrf @method('DELETE')<label for="delete_password" class="sr-only">Password</label><input id="delete_password" name="password" type="password" required autocomplete="current-password" placeholder="Password" class="block w-full rounded-lg border-gray-300 text-sm shadow-sm focus:border-red-500 focus:ring-red-500"><x-input-error :messages="$errors->userDeletion->get('password')" class="mt-2" /><div class="mt-6 flex justify-end gap-3"><button type="button" @click="showDeleteModal = false" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">Cancel</button><button type="submit" class="rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white hover:bg-red-700">Delete Account</button></div></form></div></div>
    </div>
</x-app-layout>
