<!DOCTYPE html>
<html lang="en">
<body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a">
<div style="max-width:620px;margin:0 auto;padding:28px 16px">
    <div style="background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:28px">
        <table role="presentation" style="width:100%;border-collapse:collapse;border-bottom:1px solid #e2e8f0;padding-bottom:20px">
            <tr><td><strong style="font-size:22px;color:#2e7d32">GreenPool</strong><div style="margin-top:5px;color:#64748b">E-Receipt</div></td><td style="text-align:right"><div style="font-size:12px;color:#94a3b8">TOTAL PAID</div><strong style="font-size:25px">RM {{ number_format((float) $payment->amount, 2) }}</strong></td></tr>
        </table>

        <p style="margin:24px 0 5px;color:#64748b;font-size:13px">Receipt number</p>
        <strong>{{ $payment->transaction_reference }}</strong>

        <table role="presentation" style="width:100%;margin-top:22px;border-collapse:collapse;font-size:14px">
            @foreach([
                'Paid at' => $payment->paid_at?->format('j M Y, g:i A'),
                'Passenger' => $payment->payer->name,
                'Driver' => $payment->payee->name,
                'Payment method' => $payment->methodLabel(),
                'Route' => $payment->booking->trip->departure_location.' → '.$payment->booking->trip->destination,
                'Driving distance' => $fareBreakdown ? number_format($fareBreakdown['distance_km'], 2).' km' : 'Not available',
                'Price per passenger' => 'RM '.number_format((float) $payment->booking->trip->price_per_passenger, 2),
                'Seats booked' => $payment->booking->number_of_seats,
            ] as $label => $value)
                <tr style="border-bottom:1px solid #f1f5f9"><td style="padding:11px 0;color:#64748b">{{ $label }}</td><td style="padding:11px 0;text-align:right;font-weight:600">{{ $value }}</td></tr>
            @endforeach
            <tr><td style="padding-top:16px;font-weight:700">Total</td><td style="padding-top:16px;text-align:right;font-size:18px;font-weight:700;color:#2e7d32">RM {{ number_format((float) $payment->amount, 2) }}</td></tr>
        </table>

        <p style="margin:28px 0 0;text-align:center;color:#94a3b8;font-size:12px">Generated by GreenPool after Stripe confirmed the payment.</p>
    </div>
</div>
</body>
</html>
