<x-app-layout>
<div class="px-4 py-8 sm:px-6"><form method="POST" action="{{ route('driver.vehicles.store') }}" enctype="multipart/form-data" class="mx-auto max-w-5xl rounded-2xl border bg-white p-6" x-data="{
step:1, submitting:false, plateCheckBusy:false, uploadNotice:{{ $errors->any() ? 'true' : 'false' }}, clientError:'', accountName:@js(\App\Support\DocumentIdentity::normalizeName(auth()->user()->name)), review:{}, snackbar:{show:false,message:'',timer:null}, ocrBusy:{}, ocrMessage:{}, ocrScanned:{}, ocrProblem:{}, vehiclePreviews:{}, documentPreviews:{}, aiVehicleValidationEnabled:{{ config('vehicle_vision.enabled') ? 'true' : 'false' }}, imageValidation:{}, detectedPlates:{}, autoDetectedColour:null,
init(){this.step=1;this.$watch('step',value=>{const normalized=Number(value);if(!Number.isInteger(normalized)||normalized<1||normalized>3)this.step=1})},
currentStep(){const value=Number(this.step);return Number.isInteger(value)&&value>=1&&value<=3?value:1},
fieldsForStep(){return this.currentStep()===1?['front_image','rear_image','side_image','plate_number','colour','seat_capacity']:['vehicle_geran','driving_licence','registered_owner_name','owner_identity_no','licence_name','licence_identity_no','manufacturer','model_name']},
async advance(){this.step=this.currentStep();if(this.step===2&&(!this.documentsScanned()||!this.documentDetailsReady()))return;const invalid=this.fieldsForStep().map(n=>this.$root.elements[n]).find(el=>el && !el.checkValidity());if(invalid){if(this.step===2)this.showSnackbar('The scan did not extract all required details. Choose a clearer document and scan it again.');else invalid.reportValidity();return}if(this.step===1 && (!this.vehicleImagesReady() || !await this.plateAvailable()))return;if(this.step===2 && !this.identityReady())return;if(this.step===2)this.prepareReview();this.uploadNotice=false;this.clientError='';this.step=Math.min(3,this.step+1)},
async plateAvailable(){const input=this.$root.elements.plate_number;const body=new FormData();body.append('plate_number',input.value);this.plateCheckBusy=true;try{const response=await fetch('{{ route('driver.vehicles.plate-availability') }}',{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body});const data=await response.json();if(!response.ok)throw new Error(data.message||Object.values(data.errors||{})[0]?.[0]||'Unable to check this plate number.');input.value=data.plate_number||input.value;if(!data.available){this.resetVehicleStep();this.showSnackbar(`${data.message} The selected photos and vehicle information were cleared. Please select and validate the vehicle photos again.`);this.$nextTick(()=>this.$root.elements.front_image?.focus());return false}input.setCustomValidity('');return true}catch(error){this.showSnackbar(error.message||'Unable to check this plate number. Please try again.');return false}finally{this.plateCheckBusy=false}},
async submitVehicle(){if(!this.filesReady()||!this.identityReady())return;this.submitting=true;try{const response=await fetch(this.$root.action,{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:new FormData(this.$root)});const data=await response.json().catch(()=>({}));if(!response.ok){const errors=data.errors||{};const firstKey=Object.keys(errors)[0];const stepOneFields=['front_image','rear_image','side_image','front_image_validation_token','rear_image_validation_token','side_image_validation_token','plate_number','colour','seat_capacity'];this.step=stepOneFields.includes(firstKey)?1:2;throw new Error(errors[firstKey]?.[0]||data.message||'Unable to add the vehicle. Review the highlighted information.')}window.location.assign(data.redirect_url||'{{ route('driver.vehicles.index') }}')}catch(error){this.submitting=false;this.showSnackbar(error.message||'Unable to add the vehicle. Please try again.')}},
goBack(){this.step=Math.max(1,this.step-1)},
prepareReview(){const data={};for(const element of this.$root.elements){if(element.name&&!element.name.endsWith('_validation_token')&&element.type!=='file')data[element.name]=element.value}this.review=data},
filesReady(){const vehicle=['front_image','rear_image','side_image'];const documents=['vehicle_geran','driving_licence'];if(vehicle.some(n=>!this.$root.elements[n]?.files.length)){this.step=1;this.uploadNotice=true;return false}if(documents.some(n=>!this.$root.elements[n]?.files.length)){this.step=2;this.uploadNotice=true;return false}return true},
showSnackbar(message){if(this.snackbar.timer)clearTimeout(this.snackbar.timer);this.snackbar.message=message;this.snackbar.show=true;this.snackbar.timer=setTimeout(()=>this.snackbar.show=false,8000)},
identityReady(){const value=n=>this.$root.elements[n].value.trim();const name=n=>value(n).toUpperCase().replace(/\s+/g,' ');const errors=[];if(name('registered_owner_name')!==name('licence_name'))errors.push('Registered owner name does not match the driving licence holder name.');if(name('registered_owner_name')!==this.accountName)errors.push(`Geran owner name does not match your driver account name (${this.accountName}). Update your profile to your legal name or upload the correct Geran.`);if(name('licence_name')!==this.accountName)errors.push(`Licence holder name does not match your driver account name (${this.accountName}). Update your profile to your legal name or upload the correct licence.`);if(value('owner_identity_no')!==value('licence_identity_no'))errors.push('Registered owner identity number does not match the driving licence identity number.');const expiry=value('licence_valid_until');const today=new Date();today.setHours(0,0,0,0);if(expiry&&new Date(`${expiry}T00:00:00`)<today)errors.push(`Driving licence expired on ${new Date(`${expiry}T00:00:00`).toLocaleDateString()}. Upload a renewed licence and scan it again.`);this.clientError=errors.join(' ');if(errors.length){this.step=2;this.showSnackbar(this.clientError);return false}this.snackbar.show=false;return true},
documentsScanned(){const missing=['vehicle_geran','driving_licence'].filter(name=>!this.ocrScanned[name]);if(missing.length){this.showSnackbar('Scan and prefill both the Vehicle Geran and Driving Licence before continuing.');return false}return true},
documentDetailsReady(){const definitions={vehicle_geran:{title:'Vehicle Geran / VOC',fields:{registered_owner_name:'registered owner name',owner_identity_no:'owner IC',manufacturer:'manufacturer',model_name:'model name'}},driving_licence:{title:'Driving Licence',fields:{licence_name:'licence holder name',licence_identity_no:'licence IC'}}};let valid=true;Object.entries(definitions).forEach(([document,definition])=>{const missing=Object.entries(definition.fields).filter(([field])=>!this.$root.elements[field]?.value.trim()).map(([,label])=>label);this.ocrProblem[document]=missing.length>0;this.markDocumentProblem(document,missing.length>0);if(missing.length){valid=false;this.ocrMessage[document]=`${definition.title} image problem: could not read ${missing.join(', ')}. Choose a clearer image and scan it again.`}});if(!valid){const affected=Object.entries(definitions).filter(([document])=>this.ocrProblem[document]).map(([,definition])=>definition.title);this.showSnackbar(`Problem found in: ${affected.join(' and ')}. Check the red highlighted image and scan it again.`)}return valid},
markDocumentProblem(name,problem){const box=this.$root.elements[name]?.closest('span');['border-red-500','ring-2','ring-red-100'].forEach(className=>box?.classList.toggle(className,problem))},
clearDocumentFields(name){const fields=name==='vehicle_geran'?['voc_reference_no','owner_identity_no','registered_owner_name','owner_address','chassis_no','engine_no','manufacturer','model_name','engine_capacity','fuel_type','origin_status','usage_class','body_type','manufacturing_year','registration_date','bdm','bgk','btm','registration_condition_1','registration_condition_2','registration_condition_3','brand','model']:['licence_name','licence_identity_no','date_of_birth','nationality','licence_class','licence_valid_from','licence_valid_until','licence_address'];fields.forEach(field=>{const input=this.$root.elements[field];if(input)input.value=''})},
previewVehicleImage(name,file){if(!file)return;if(this.autoDetectedColour&&this.$root.elements.colour.value===this.autoDetectedColour)this.$root.elements.colour.value='';this.autoDetectedColour=null;const view={front_image:'FRONT',rear_image:'REAR',side_image:'SIDE'}[name];const previousPlate=this.detectedPlates[view];delete this.detectedPlates[view];if(previousPlate&&this.$root.elements.plate_number.value===previousPlate&&!Object.values(this.detectedPlates).includes(previousPlate))this.$root.elements.plate_number.value='';const previous=this.vehiclePreviews[name]?.url;if(previous)URL.revokeObjectURL(previous);this.vehiclePreviews[name]={url:URL.createObjectURL(file),fileName:file.name};this.imageValidation[name]={busy:false,accepted:false,message:'Photo changed. Validate this image before continuing.',token:null};const token=this.$root.elements[`${name}_validation_token`];if(token)token.value=''},
vehicleImagesReady(){if(!this.aiVehicleValidationEnabled)return true;const missing=['front_image','rear_image','side_image'].filter(name=>!this.imageValidation[name]?.accepted);if(missing.length){this.showSnackbar('Validate the front, rear, and side vehicle photos before continuing.');return false}return true},
resetVehicleStep(){['front_image','rear_image','side_image'].forEach(name=>{const preview=this.vehiclePreviews[name];if(preview?.url)URL.revokeObjectURL(preview.url);const fileInput=this.$root.elements[name];if(fileInput)fileInput.value='';const token=this.$root.elements[`${name}_validation_token`];if(token)token.value=''});['plate_number','brand','model','colour'].forEach(name=>{const input=this.$root.elements[name];if(input)input.value=''});const seats=this.$root.elements.seat_capacity;if(seats)seats.value='4';this.vehiclePreviews={};this.imageValidation={};this.detectedPlates={};this.autoDetectedColour=null;this.step=1},
checkVehicleConsistency(){const accepted=Object.values(this.imageValidation).filter(result=>result?.accepted);const reliable=accepted.filter(result=>result?.colourReliable&&result?.colourGroup);const groups=[...new Set(reliable.map(result=>result.colourGroup))];if(groups.length>1){const visibleColours=[...new Set(reliable.map(result=>result.detectedColour))];const message=`The vehicle colours do not match (${visibleColours.join(' / ')}), so the photos may show different cars. All vehicle information was cleared. Please select front, rear, and side photos of the same vehicle again.`;this.resetVehicleStep();this.showSnackbar(message);return false}if(accepted.length===3&&reliable.length===3&&groups.length===1){const scores={};reliable.forEach(result=>{scores[result.detectedColour]=(scores[result.detectedColour]||0)+Number(result.colourConfidence||0)});const consensus=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0]?.[0];const input=this.$root.elements.colour;if(consensus&&input&&!input.value){input.value=consensus;this.autoDetectedColour=consensus;input.dispatchEvent(new Event('input',{bubbles:true}))}}return true},
applyDetectedPlate(view,plate){if(!plate)return;this.detectedPlates[view]=plate;const readings=[...new Set(Object.values(this.detectedPlates).filter(Boolean))];if(readings.length>1){const message=`The vehicle photos produced different plate readings (${readings.join(' / ')}). All vehicle information was cleared. Please select three photos of the same vehicle again.`;this.resetVehicleStep();this.showSnackbar(message);return}const input=this.$root.elements.plate_number;input.value=plate;input.dispatchEvent(new Event('input',{bubbles:true}))},
async validateVehicleImage(name,view){const file=this.$root.elements[name]?.files[0];if(!file){this.showSnackbar('Choose a vehicle photo first.');return}this.imageValidation[name]={busy:true,accepted:false,message:'Checking this photo locally and reading the plate…',token:null};const body=new FormData();body.append('image',file);body.append('expected_view',view);try{const response=await fetch('{{ route('driver.vehicles.images.validate') }}',{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body});const data=await response.json();if(!response.ok)throw new Error(data.message||Object.values(data.errors||{})[0]?.[0]||'Unable to validate photo.');this.imageValidation[name]={busy:false,accepted:data.accepted,message:data.message+(data.accepted&&!data.plate_number?' No clear plate number was found in this photo.':''),token:data.token,detectedColour:data.detected_colour,colourGroup:data.colour_group||data.detected_colour,colourConfidence:data.colour_confidence,colourReliable:data.colour_reliable};this.$root.elements[`${name}_validation_token`].value=data.token||'';if(data.accepted){if(this.checkVehicleConsistency())this.applyDetectedPlate(view,data.plate_number)}else this.showSnackbar(data.message||`The ${view.toLowerCase()} photo was not accepted.`)}catch(error){this.imageValidation[name]={busy:false,accepted:false,message:error.message,token:null};this.showSnackbar(error.message)}},
previewDocument(name,file){if(!file)return;this.clearDocumentFields(name);const previous=this.documentPreviews[name]?.url;if(previous)URL.revokeObjectURL(previous);this.documentPreviews[name]={url:URL.createObjectURL(file),fileName:file.name};this.ocrMessage[name]='';this.ocrScanned[name]=false;this.ocrProblem[name]=false;this.markDocumentProblem(name,false)},
dateValue(value){const match=(value||'').match(/^(\d{2})[\/.\-](\d{2})[\/.\-](\d{4})$/);return match?`${match[3]}-${match[2]}-${match[1]}`:value},
applyOcr(type,fields){const maps={DRIVING_LICENCE:{name:'licence_name',identity_no:'licence_identity_no',date_of_birth:'date_of_birth',nationality:'nationality',licence_class:'licence_class',valid_from:'licence_valid_from',valid_until:'licence_valid_until',address:'licence_address'},VEHICLE_GERAN:{voc_reference_no:'voc_reference_no',registration_no:'plate_number',owner_identity_no:'owner_identity_no',registered_owner_name:'registered_owner_name',owner_address:'owner_address',chassis_no:'chassis_no',engine_no:'engine_no',manufacturer:'manufacturer',model_name:'model_name',engine_capacity:'engine_capacity',fuel_type:'fuel_type',origin_status:'origin_status',usage_class:'usage_class',body_type:'body_type',manufacturing_year:'manufacturing_year',registration_date:'registration_date',bdm:'bdm',bgk:'bgk',btm:'btm',registration_condition_1:'registration_condition_1',registration_condition_2:'registration_condition_2',registration_condition_3:'registration_condition_3'}};Object.entries(maps[type]).forEach(([source,target])=>{const value=fields[source]?.value;const input=this.$root.elements[target];if(input&&value!==null&&value!==undefined&&value!=='')input.value=input.type==='date'?this.dateValue(value):value});if(type==='VEHICLE_GERAN'){this.$root.elements.brand.value=this.$root.elements.manufacturer.value;this.$root.elements.model.value=this.$root.elements.model_name.value}},
async scanDocument(inputName,type){const file=this.$root.elements[inputName]?.files[0];if(!file){this.ocrMessage[inputName]='Choose an image first.';return}this.ocrProblem[inputName]=false;this.markDocumentProblem(inputName,false);this.ocrScanned[inputName]=false;this.ocrBusy[inputName]=true;this.ocrMessage[inputName]='Scanning locally…';const body=new FormData();body.append('document',file);body.append('expected_document_type',type);try{const response=await fetch('{{ route('driver.vehicles.documents.ocr') }}',{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body});const data=await response.json();if(!response.ok)throw new Error(data.message||Object.values(data.errors||{})[0]?.[0]||'Unable to scan document.');this.applyOcr(type,data.fields);this.ocrScanned[inputName]=true;this.ocrMessage[inputName]='Scan complete. Details will be shown on Step 3 for review.'}catch(error){this.ocrProblem[inputName]=true;this.markDocumentProblem(inputName,true);this.ocrScanned[inputName]=false;this.ocrMessage[inputName]=error.message}finally{this.ocrBusy[inputName]=false}}
}" @submit.prevent="submitVehicle()">
@csrf
<a href="{{ route('driver.vehicles.index') }}" class="text-sm font-semibold text-[#2E7D32]">← Back to vehicles</a>
<header class="my-6"><p class="text-xs font-bold uppercase tracking-widest text-[#2E7D32]">Step <span x-text="currentStep()"></span> of 3</p><h1 class="mt-2 text-2xl font-bold" x-text="currentStep()===1?'Vehicle photos':(currentStep()===2?'Vehicle documents':'Check details')"></h1><p class="mt-2 text-sm text-gray-600">Scan each document to prefill the form, then review and correct every extracted value before submission.</p></header>
@if($errors->any())<div class="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><b>Please correct these details.</b><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div x-cloak x-show="uploadNotice" class="mb-6 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900" role="alert"><b>Please upload the five images again.</b><p class="mt-1">Browsers clear selected files after a server validation error for security. Your typed details are preserved.</p></div>

<section x-show="currentStep()===1" class="space-y-6">
<div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">Use landscape photos in good lighting. The whole car must be visible; front and rear plates must be sharp and unobstructed. Minimum 800 × 450, maximum 8 MB.</div>
<div class="grid gap-5 md:grid-cols-3">@foreach(['front_image'=>['Front car image','FRONT'],'rear_image'=>['Rear car image','REAR'],'side_image'=>['Side car image','SIDE']] as $name=>$photo)<div><label class="block text-sm font-semibold">{{ $photo[0] }} *<span class="relative mt-2 flex aspect-[4/3] cursor-pointer items-center justify-center overflow-hidden rounded-xl border-2 border-dashed bg-gray-50 text-center text-gray-600"><input name="{{ $name }}" type="file" accept="image/jpeg,image/png" required class="sr-only" @change="previewVehicleImage('{{ $name }}',$event.target.files[0])"><img x-cloak x-show="vehiclePreviews['{{ $name }}']" :src="vehiclePreviews['{{ $name }}']?.url" alt="{{ $photo[0] }} preview" class="h-full w-full object-cover"><span x-show="!vehiclePreviews['{{ $name }}']" class="p-4">Choose clear JPG or PNG photo</span><span x-cloak x-show="vehiclePreviews['{{ $name }}']" x-text="vehiclePreviews['{{ $name }}']?.fileName" class="absolute inset-x-2 bottom-2 truncate rounded-md bg-black/65 px-2 py-1 text-xs font-medium text-white"></span></span></label><input type="hidden" name="{{ $name }}_validation_token"><template x-if="aiVehicleValidationEnabled"><div><button type="button" @click="validateVehicleImage('{{ $name }}','{{ $photo[1] }}')" :disabled="imageValidation['{{ $name }}']?.busy" class="mt-3 rounded-lg border border-[#2E7D32] px-3 py-2 text-sm font-semibold text-[#2E7D32] disabled:opacity-50" x-text="imageValidation['{{ $name }}']?.busy?'Checking…':'Validate photo'"></button><p x-show="imageValidation['{{ $name }}']?.message" x-text="imageValidation['{{ $name }}']?.message" :class="imageValidation['{{ $name }}']?.accepted?'text-green-700':'font-medium text-red-700'" class="mt-2 text-sm" role="status"></p></div></template>@error($name)<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</div>@endforeach</div>
<input type="hidden" name="brand" value="{{ old('brand') }}"><input type="hidden" name="model" value="{{ old('model') }}">
<div class="grid gap-5 md:grid-cols-2"><label class="text-sm font-semibold">Plate number <span class="font-normal text-gray-500">(detected from photos)</span><input name="plate_number" value="{{ old('plate_number') }}" required readonly maxlength="20" @input="$event.target.setCustomValidity('')" class="mt-2 block w-full cursor-not-allowed rounded-xl border-gray-300 bg-gray-100 text-gray-700"></label><label class="text-sm font-semibold">Colour <span class="font-normal text-gray-500">(detected from photos)</span><input name="colour" value="{{ old('colour') }}" required readonly maxlength="20" class="mt-2 block w-full cursor-not-allowed rounded-xl border-gray-300 bg-gray-100 text-gray-700"></label><label class="text-sm font-semibold">Passenger seats<select name="seat_capacity" class="mt-2 block w-full rounded-xl border-gray-300">@foreach(range(1,4) as $n)<option value="{{ $n }}" @selected(old('seat_capacity',4)==$n)>{{ $n }}</option>@endforeach</select></label></div>
</section>

<section x-cloak x-show="currentStep()===2" class="space-y-7 [&>fieldset]:hidden">
<div class="grid gap-5 md:grid-cols-2">@foreach(['vehicle_geran'=>['Vehicle Geran / VOC','VEHICLE_GERAN'],'driving_licence'=>['Driving Licence','DRIVING_LICENCE']] as $name=>$document)<div><label class="text-sm font-semibold">{{ $document[0] }} *<span class="relative mt-2 flex aspect-[16/10] cursor-pointer items-center justify-center overflow-hidden rounded-xl border-2 border-dashed bg-gray-50 text-center text-gray-600"><input name="{{ $name }}" type="file" accept="image/jpeg,image/png" required class="sr-only" @change="previewDocument('{{ $name }}',$event.target.files[0])"><img x-cloak x-show="documentPreviews['{{ $name }}']" :src="documentPreviews['{{ $name }}']?.url" alt="{{ $document[0] }} preview" class="h-full w-full object-contain"><span x-show="!documentPreviews['{{ $name }}']" class="p-4">Choose clear, full JPG or PNG (minimum 500 × 300)</span><span x-cloak x-show="documentPreviews['{{ $name }}']" x-text="documentPreviews['{{ $name }}']?.fileName" class="absolute inset-x-2 bottom-2 truncate rounded-md bg-black/65 px-2 py-1 text-xs font-medium text-white"></span></span></label><button type="button" @click="scanDocument('{{ $name }}','{{ $document[1] }}')" :disabled="ocrBusy['{{ $name }}']" class="mt-3 rounded-lg border border-[#2E7D32] px-4 py-2 text-sm font-semibold text-[#2E7D32] disabled:opacity-50" x-text="ocrBusy['{{ $name }}']?'Scanning…':'Scan & prefill'"></button><p x-show="ocrMessage['{{ $name }}']" x-text="ocrMessage['{{ $name }}']" class="mt-2 text-sm text-gray-600" role="status"></p></div>@endforeach</div>
<fieldset class="rounded-xl border p-5"><legend class="px-2 font-bold">Identity match (required)</legend><div class="grid gap-5 md:grid-cols-2">@foreach(['registered_owner_name'=>'Geran registered owner name','owner_identity_no'=>'Geran owner IC','licence_name'=>'Driving licence name','licence_identity_no'=>'Driving licence IC'] as $name=>$label)<label class="text-sm font-semibold">{{ $label }}<input name="{{ $name }}" value="{{ old($name) }}" required @if(str_contains($name,'identity')) inputmode="numeric" pattern="[0-9]{12}" maxlength="12" @endif class="mt-2 block w-full rounded-xl border-gray-300 uppercase">@error($name)<span class="mt-1 block text-red-600">{{ $message }}</span>@enderror</label>@endforeach</div></fieldset>
<fieldset class="rounded-xl border p-5"><legend class="px-2 font-bold">Geran details</legend><div class="grid gap-5 md:grid-cols-3">@foreach(['voc_reference_no'=>'VOC reference no.','chassis_no'=>'Chassis no.','engine_no'=>'Engine no.','manufacturer'=>'Manufacturer','model_name'=>'Model name','engine_capacity'=>'Engine capacity (cc)','fuel_type'=>'Fuel type','origin_status'=>'Origin status','usage_class'=>'Usage class','body_type'=>'Body type','manufacturing_year'=>'Manufacturing year','registration_date'=>'Registration date','bdm'=>'BDM','bgk'=>'BGK','btm'=>'BTM'] as $name=>$label)<label class="text-sm font-semibold">{{ $label }}@if(in_array($name,['manufacturer','model_name'],true)) * @endif<input name="{{ $name }}" value="{{ old($name) }}" @if(in_array($name,['manufacturer','model_name'],true)) required x-on:input="$root.elements.{{ $name === 'manufacturer' ? 'brand' : 'model' }}.value = $event.target.value" @endif @if(str_contains($name,'date')) type="date" @endif class="mt-2 block w-full rounded-xl border-gray-300"></label>@endforeach</div><label class="mt-5 block text-sm font-semibold">Owner address<textarea name="owner_address" rows="3" class="mt-2 block w-full rounded-xl border-gray-300">{{ old('owner_address') }}</textarea></label><div class="mt-5 grid gap-5 md:grid-cols-3">@foreach(range(1,3) as $number)<label class="text-sm font-semibold">Registration condition {{ $number }}<input name="registration_condition_{{ $number }}" value="{{ old('registration_condition_'.$number) }}" class="mt-2 block w-full rounded-xl border-gray-300"></label>@endforeach</div></fieldset>
<fieldset class="rounded-xl border p-5"><legend class="px-2 font-bold">Driving licence details</legend><div class="grid gap-5 md:grid-cols-3">@foreach(['date_of_birth'=>'Date of birth','nationality'=>'Nationality','licence_class'=>'Licence class','licence_valid_from'=>'Valid from','licence_valid_until'=>'Valid until'] as $name=>$label)<label class="text-sm font-semibold">{{ $label }}<input name="{{ $name }}" value="{{ old($name) }}" @if(str_contains($name,'date') || str_contains($name,'valid_')) type="date" @endif class="mt-2 block w-full rounded-xl border-gray-300"></label>@endforeach</div><label class="mt-5 block text-sm font-semibold">Licence address<textarea name="licence_address" rows="3" class="mt-2 block w-full rounded-xl border-gray-300">{{ old('licence_address') }}</textarea></label></fieldset>
</section>

<section x-cloak x-show="currentStep()===3" class="space-y-5">
<div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Review every extracted value before submission. Use Back to correct anything that is missing or inaccurate.</div>
@foreach([
    'Vehicle details' => ['plate_number'=>'Plate number','brand'=>'Brand','model'=>'Model','colour'=>'Colour','seat_capacity'=>'Passenger seats'],
    'Identity match' => ['registered_owner_name'=>'Geran owner name','owner_identity_no'=>'Geran owner IC','licence_name'=>'Licence holder name','licence_identity_no'=>'Licence holder IC'],
    'Geran details' => ['voc_reference_no'=>'VOC reference no.','chassis_no'=>'Chassis no.','engine_no'=>'Engine no.','manufacturer'=>'Manufacturer','model_name'=>'Geran model','engine_capacity'=>'Engine capacity (cc)','fuel_type'=>'Fuel type','origin_status'=>'Origin status','usage_class'=>'Usage class','body_type'=>'Body type','manufacturing_year'=>'Manufacturing year','registration_date'=>'Registration date','bdm'=>'BDM','bgk'=>'BGK','btm'=>'BTM','owner_address'=>'Owner address','registration_condition_1'=>'Registration condition 1','registration_condition_2'=>'Registration condition 2','registration_condition_3'=>'Registration condition 3'],
    'Driving licence details' => ['date_of_birth'=>'Date of birth','nationality'=>'Nationality','licence_class'=>'Licence class','licence_valid_from'=>'Valid from','licence_valid_until'=>'Valid until','licence_address'=>'Licence address'],
] as $reviewTitle => $reviewFields)
<fieldset class="rounded-xl border p-5"><legend class="px-2 font-bold">{{ $reviewTitle }}</legend><div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">@foreach($reviewFields as $reviewName => $reviewLabel)<div @class(['md:col-span-2 lg:col-span-3' => str_contains($reviewName, 'address')])><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">{{ $reviewLabel }}</p><p class="mt-1 whitespace-pre-line break-words font-semibold text-gray-900" x-text="review['{{ $reviewName }}'] || '—'"></p></div>@endforeach</div></fieldset>
@endforeach
</section>

<footer class="mt-8 flex flex-wrap justify-end gap-3 border-t pt-6"><a href="{{ route('driver.vehicles.index') }}" class="inline-flex min-h-11 items-center rounded-xl border px-5 text-sm font-semibold">Cancel</a><button x-cloak x-show="currentStep()>1" type="button" @click="goBack()" class="min-h-11 rounded-xl border px-5 font-semibold">Back</button><button x-show="currentStep()<3" type="button" @click="advance()" :disabled="plateCheckBusy" x-text="plateCheckBusy ? 'Checking plate…' : 'Continue'" class="min-h-11 rounded-xl bg-[#2E7D32] px-5 font-semibold text-white disabled:cursor-wait disabled:opacity-60">Continue</button><button x-cloak x-show="currentStep()===3" type="submit" :disabled="submitting" class="min-h-11 rounded-xl bg-[#2E7D32] px-5 font-semibold text-white disabled:opacity-60">Add vehicle</button></footer>
<div x-cloak x-show="snackbar.show" x-transition:enter="transition ease-out duration-200" x-transition:enter-start="translate-y-4 opacity-0" x-transition:enter-end="translate-y-0 opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="translate-y-0 opacity-100" x-transition:leave-end="translate-y-4 opacity-0" class="fixed inset-x-4 bottom-5 z-50 mx-auto flex max-w-xl items-start gap-3 rounded-xl bg-gray-950 px-4 py-3 text-sm text-white shadow-2xl sm:inset-x-auto sm:right-6" role="alert" aria-live="assertive"><span class="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-red-500 font-bold" aria-hidden="true">!</span><p x-text="snackbar.message" class="min-w-0 flex-1 leading-5"></p><button type="button" @click="snackbar.show=false" class="rounded p-1 text-gray-300 hover:bg-white/10 hover:text-white" aria-label="Dismiss message">×</button></div>
</form></div>
</x-app-layout>
