<x-app-layout>
<div class="px-4 py-8 sm:px-6"><form method="POST" action="{{ route('driver.vehicles.store') }}" enctype="multipart/form-data" class="mx-auto max-w-5xl rounded-2xl border bg-white p-6" x-data="{
step:1, submitting:false, uploadNotice:{{ $errors->any() ? 'true' : 'false' }}, clientError:'', snackbar:{show:false,message:'',timer:null}, ocrBusy:{}, ocrMessage:{}, vehiclePreviews:{}, documentPreviews:{},
fieldsForStep(){return this.step===1?['front_image','rear_image','side_image','plate_number','brand','model','colour','seat_capacity']:['vehicle_geran','driving_licence','registered_owner_name','owner_identity_no','licence_name','licence_identity_no']},
advance(){const invalid=this.fieldsForStep().map(n=>this.$root.elements[n]).find(el=>el && !el.checkValidity());if(invalid){invalid.reportValidity();return}if(this.step===2 && !this.identityReady())return;this.uploadNotice=false;this.clientError='';this.step++},
filesReady(){const vehicle=['front_image','rear_image','side_image'];const documents=['vehicle_geran','driving_licence'];if(vehicle.some(n=>!this.$root.elements[n]?.files.length)){this.step=1;this.uploadNotice=true;return false}if(documents.some(n=>!this.$root.elements[n]?.files.length)){this.step=2;this.uploadNotice=true;return false}return true},
showSnackbar(message){if(this.snackbar.timer)clearTimeout(this.snackbar.timer);this.snackbar.message=message;this.snackbar.show=true;this.snackbar.timer=setTimeout(()=>this.snackbar.show=false,8000)},
identityReady(){const value=n=>this.$root.elements[n].value.trim();const name=n=>value(n).toUpperCase().replace(/\s+/g,' ');const errors=[];if(name('registered_owner_name')!==name('licence_name'))errors.push('Registered owner name does not match the driving licence holder name.');if(value('owner_identity_no')!==value('licence_identity_no'))errors.push('Registered owner identity number does not match the driving licence identity number.');this.clientError=errors.join(' ');if(errors.length){this.step=2;this.showSnackbar(this.clientError);return false}this.snackbar.show=false;return true},
previewVehicleImage(name,file){if(!file)return;const previous=this.vehiclePreviews[name]?.url;if(previous)URL.revokeObjectURL(previous);this.vehiclePreviews[name]={url:URL.createObjectURL(file),fileName:file.name}},
previewDocument(name,file){if(!file)return;const previous=this.documentPreviews[name]?.url;if(previous)URL.revokeObjectURL(previous);this.documentPreviews[name]={url:URL.createObjectURL(file),fileName:file.name};this.ocrMessage[name]=''},
dateValue(value){const match=(value||'').match(/^(\d{2})[\/.\-](\d{2})[\/.\-](\d{4})$/);return match?`${match[3]}-${match[2]}-${match[1]}`:value},
applyOcr(type,fields){const maps={DRIVING_LICENCE:{name:'licence_name',identity_no:'licence_identity_no',date_of_birth:'date_of_birth',nationality:'nationality',licence_class:'licence_class',valid_from:'licence_valid_from',valid_until:'licence_valid_until',address:'licence_address'},VEHICLE_GERAN:{voc_reference_no:'voc_reference_no',registration_no:'plate_number',owner_identity_no:'owner_identity_no',registered_owner_name:'registered_owner_name',owner_address:'owner_address',chassis_no:'chassis_no',engine_no:'engine_no',manufacturer:'manufacturer',model_name:'model_name',engine_capacity:'engine_capacity',fuel_type:'fuel_type',origin_status:'origin_status',usage_class:'usage_class',body_type:'body_type',manufacturing_year:'manufacturing_year',registration_date:'registration_date',bdm:'bdm',bgk:'bgk',btm:'btm',registration_condition_1:'registration_condition_1',registration_condition_2:'registration_condition_2',registration_condition_3:'registration_condition_3'}};Object.entries(maps[type]).forEach(([source,target])=>{const value=fields[source]?.value;const input=this.$root.elements[target];if(input&&value!==null&&value!==undefined&&value!=='')input.value=input.type==='date'?this.dateValue(value):value})},
async scanDocument(inputName,type){const file=this.$root.elements[inputName]?.files[0];if(!file){this.ocrMessage[inputName]='Choose an image first.';return}this.ocrBusy[inputName]=true;this.ocrMessage[inputName]='Scanning locally…';const body=new FormData();body.append('document',file);body.append('expected_document_type',type);try{const response=await fetch('{{ route('driver.vehicles.documents.ocr') }}',{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body});const data=await response.json();if(!response.ok)throw new Error(data.message||Object.values(data.errors||{})[0]?.[0]||'Unable to scan document.');this.applyOcr(type,data.fields);this.ocrMessage[inputName]=data.requires_review?'Fields extracted. Review all highlighted document details carefully.':'Fields extracted. Review and confirm every value.'}catch(error){this.ocrMessage[inputName]=error.message}finally{this.ocrBusy[inputName]=false}}
}" @submit="if(!filesReady() || !identityReady()){$event.preventDefault()}else{submitting=true}">
@csrf
<a href="{{ route('driver.vehicles.index') }}" class="text-sm font-semibold text-[#2E7D32]">← Back to vehicles</a>
<header class="my-6"><p class="text-xs font-bold uppercase tracking-widest text-[#2E7D32]">Step <span x-text="step"></span> of 3</p><h1 class="mt-2 text-2xl font-bold" x-text="step===1?'Vehicle photos':(step===2?'Vehicle documents':'Check details')"></h1><p class="mt-2 text-sm text-gray-600">Scan each document to prefill the form, then review and correct every extracted value before submission.</p></header>
@if($errors->any())<div class="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><b>Please correct these details.</b><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div x-cloak x-show="uploadNotice" class="mb-6 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900" role="alert"><b>Please upload the five images again.</b><p class="mt-1">Browsers clear selected files after a server validation error for security. Your typed details are preserved.</p></div>

<section x-show="step===1" class="space-y-6">
<div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">Use landscape photos in good lighting. The whole car must be visible; front and rear plates must be sharp and unobstructed. Minimum 800 × 450, maximum 8 MB.</div>
<div class="grid gap-5 md:grid-cols-3">@foreach(['front_image'=>'Front car image','rear_image'=>'Rear car image','side_image'=>'Side car image'] as $name=>$label)<label class="block text-sm font-semibold">{{ $label }} *<span class="relative mt-2 flex aspect-[4/3] cursor-pointer items-center justify-center overflow-hidden rounded-xl border-2 border-dashed bg-gray-50 text-center text-gray-600"><input name="{{ $name }}" type="file" accept="image/jpeg,image/png,image/webp" required class="sr-only" @change="previewVehicleImage('{{ $name }}',$event.target.files[0])"><img x-cloak x-show="vehiclePreviews['{{ $name }}']" :src="vehiclePreviews['{{ $name }}']?.url" alt="{{ $label }} preview" class="h-full w-full object-cover"><span x-show="!vehiclePreviews['{{ $name }}']" class="p-4">Choose clear photo</span><span x-cloak x-show="vehiclePreviews['{{ $name }}']" x-text="vehiclePreviews['{{ $name }}']?.fileName" class="absolute inset-x-2 bottom-2 truncate rounded-md bg-black/65 px-2 py-1 text-xs font-medium text-white"></span></span>@error($name)<span class="mt-1 block text-red-600">{{ $message }}</span>@enderror</label>@endforeach</div>
<div class="grid gap-5 md:grid-cols-2">@foreach(['plate_number'=>'Plate number','brand'=>'Brand','model'=>'Model','colour'=>'Colour'] as $name=>$label)<label class="text-sm font-semibold">{{ $label }}<input name="{{ $name }}" value="{{ old($name) }}" required maxlength="50" class="mt-2 block w-full rounded-xl border-gray-300"></label>@endforeach<label class="text-sm font-semibold">Passenger seats<select name="seat_capacity" class="mt-2 block w-full rounded-xl border-gray-300">@foreach(range(1,4) as $n)<option value="{{ $n }}" @selected(old('seat_capacity',4)==$n)>{{ $n }}</option>@endforeach</select></label></div>
</section>

<section x-cloak x-show="step===2" class="space-y-7">
<div class="grid gap-5 md:grid-cols-2">@foreach(['vehicle_geran'=>['Vehicle Geran / VOC','VEHICLE_GERAN'],'driving_licence'=>['Driving Licence','DRIVING_LICENCE']] as $name=>$document)<div><label class="text-sm font-semibold">{{ $document[0] }} *<span class="relative mt-2 flex aspect-[16/10] cursor-pointer items-center justify-center overflow-hidden rounded-xl border-2 border-dashed bg-gray-50 text-center text-gray-600"><input name="{{ $name }}" type="file" accept="image/jpeg,image/png" required class="sr-only" @change="previewDocument('{{ $name }}',$event.target.files[0])"><img x-cloak x-show="documentPreviews['{{ $name }}']" :src="documentPreviews['{{ $name }}']?.url" alt="{{ $document[0] }} preview" class="h-full w-full object-contain"><span x-show="!documentPreviews['{{ $name }}']" class="p-4">Choose clear, full JPG or PNG (minimum 500 × 300)</span><span x-cloak x-show="documentPreviews['{{ $name }}']" x-text="documentPreviews['{{ $name }}']?.fileName" class="absolute inset-x-2 bottom-2 truncate rounded-md bg-black/65 px-2 py-1 text-xs font-medium text-white"></span></span></label><button type="button" @click="scanDocument('{{ $name }}','{{ $document[1] }}')" :disabled="ocrBusy['{{ $name }}']" class="mt-3 rounded-lg border border-[#2E7D32] px-4 py-2 text-sm font-semibold text-[#2E7D32] disabled:opacity-50" x-text="ocrBusy['{{ $name }}']?'Scanning…':'Scan & prefill'"></button><p x-show="ocrMessage['{{ $name }}']" x-text="ocrMessage['{{ $name }}']" class="mt-2 text-sm text-gray-600" role="status"></p></div>@endforeach</div>
<fieldset class="rounded-xl border p-5"><legend class="px-2 font-bold">Identity match (required)</legend><div class="grid gap-5 md:grid-cols-2">@foreach(['registered_owner_name'=>'Geran registered owner name','owner_identity_no'=>'Geran owner IC','licence_name'=>'Driving licence name','licence_identity_no'=>'Driving licence IC'] as $name=>$label)<label class="text-sm font-semibold">{{ $label }}<input name="{{ $name }}" value="{{ old($name) }}" required @if(str_contains($name,'identity')) inputmode="numeric" pattern="[0-9]{12}" maxlength="12" @endif class="mt-2 block w-full rounded-xl border-gray-300 uppercase">@error($name)<span class="mt-1 block text-red-600">{{ $message }}</span>@enderror</label>@endforeach</div></fieldset>
<fieldset class="rounded-xl border p-5"><legend class="px-2 font-bold">Geran details</legend><div class="grid gap-5 md:grid-cols-3">@foreach(['voc_reference_no'=>'VOC reference no.','chassis_no'=>'Chassis no.','engine_no'=>'Engine no.','manufacturer'=>'Manufacturer','model_name'=>'Model name','engine_capacity'=>'Engine capacity (cc)','fuel_type'=>'Fuel type','origin_status'=>'Origin status','usage_class'=>'Usage class','body_type'=>'Body type','manufacturing_year'=>'Manufacturing year','registration_date'=>'Registration date','bdm'=>'BDM','bgk'=>'BGK','btm'=>'BTM'] as $name=>$label)<label class="text-sm font-semibold">{{ $label }}<input name="{{ $name }}" value="{{ old($name) }}" @if(str_contains($name,'date')) type="date" @endif class="mt-2 block w-full rounded-xl border-gray-300"></label>@endforeach</div><label class="mt-5 block text-sm font-semibold">Owner address<textarea name="owner_address" rows="3" class="mt-2 block w-full rounded-xl border-gray-300">{{ old('owner_address') }}</textarea></label><div class="mt-5 grid gap-5 md:grid-cols-3">@foreach(range(1,3) as $number)<label class="text-sm font-semibold">Registration condition {{ $number }}<input name="registration_condition_{{ $number }}" value="{{ old('registration_condition_'.$number) }}" class="mt-2 block w-full rounded-xl border-gray-300"></label>@endforeach</div></fieldset>
<fieldset class="rounded-xl border p-5"><legend class="px-2 font-bold">Driving licence details</legend><div class="grid gap-5 md:grid-cols-3">@foreach(['date_of_birth'=>'Date of birth','nationality'=>'Nationality','licence_class'=>'Licence class','licence_valid_from'=>'Valid from','licence_valid_until'=>'Valid until'] as $name=>$label)<label class="text-sm font-semibold">{{ $label }}<input name="{{ $name }}" value="{{ old($name) }}" @if(str_contains($name,'date') || str_contains($name,'valid_')) type="date" @endif class="mt-2 block w-full rounded-xl border-gray-300"></label>@endforeach</div><label class="mt-5 block text-sm font-semibold">Licence address<textarea name="licence_address" rows="3" class="mt-2 block w-full rounded-xl border-gray-300">{{ old('licence_address') }}</textarea></label></fieldset>
</section>

<section x-cloak x-show="step===3" class="space-y-5"><div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Review every field. The server rejects the submission unless both normalized names and both 12-digit IC numbers match exactly.</div><div class="grid gap-4 rounded-xl border p-5 md:grid-cols-2"><template x-for="field in ['plate_number','brand','model','registered_owner_name','owner_identity_no','licence_name','licence_identity_no']"><div><p class="text-xs uppercase text-gray-500" x-text="field.replaceAll('_',' ')"></p><p class="font-semibold" x-text="document.querySelector('[name='+field+']')?.value||'—'"></p></div></template></div></section>

<footer class="mt-8 flex flex-wrap justify-end gap-3 border-t pt-6"><a href="{{ route('driver.vehicles.index') }}" class="inline-flex min-h-11 items-center rounded-xl border px-5 text-sm font-semibold">Cancel</a><button x-cloak x-show="step>1" type="button" @click="step--" class="min-h-11 rounded-xl border px-5 font-semibold">Back</button><button x-show="step<3" type="button" @click="advance()" class="min-h-11 rounded-xl bg-[#2E7D32] px-5 font-semibold text-white">Continue</button><button x-cloak x-show="step===3" type="submit" :disabled="submitting" class="min-h-11 rounded-xl bg-[#2E7D32] px-5 font-semibold text-white disabled:opacity-60">Add vehicle</button></footer>
<div x-cloak x-show="snackbar.show" x-transition:enter="transition ease-out duration-200" x-transition:enter-start="translate-y-4 opacity-0" x-transition:enter-end="translate-y-0 opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="translate-y-0 opacity-100" x-transition:leave-end="translate-y-4 opacity-0" class="fixed inset-x-4 bottom-5 z-50 mx-auto flex max-w-xl items-start gap-3 rounded-xl bg-gray-950 px-4 py-3 text-sm text-white shadow-2xl sm:inset-x-auto sm:right-6" role="alert" aria-live="assertive"><span class="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-red-500 font-bold" aria-hidden="true">!</span><p x-text="snackbar.message" class="min-w-0 flex-1 leading-5"></p><button type="button" @click="snackbar.show=false" class="rounded p-1 text-gray-300 hover:bg-white/10 hover:text-white" aria-label="Dismiss message">×</button></div>
</form></div>
</x-app-layout>
