<x-app-layout>
    <div class="px-4 py-8 sm:px-6 lg:px-8">
        <div class="mx-auto max-w-3xl">
            <a href="{{ route('driver.vehicles.show', $vehicle) }}" class="text-sm font-semibold text-[#2E7D32] hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2E7D32]">← Back to vehicle details</a>

            <div class="mt-5 rounded-2xl border border-gray-200 bg-white p-6 sm:p-8">
                <div class="mb-8">
                    <h2 class="text-xl font-bold text-gray-900">Edit vehicle</h2>
                    <p class="mt-1 text-sm text-gray-600">Update the registered information for {{ $vehicle->plate_number }}.</p>
                </div>

                <form method="POST" action="{{ route('driver.vehicles.update', $vehicle) }}" enctype="multipart/form-data" x-data="{
                    submitting: false, showPhotoExamples: false, showGeranExample: false, original: @js(['plate_number' => $vehicle->plate_number, 'brand' => $vehicle->brand, 'model' => $vehicle->model, 'colour' => $vehicle->colour]), fields: @js(['plate_number' => old('plate_number', $vehicle->plate_number), 'brand' => old('brand', $vehicle->brand), 'model' => old('model', $vehicle->model), 'colour' => old('colour', $vehicle->colour)]),
                    previews: {}, validated: {}, busy: {}, photoResults: {}, detectedPlatePreview: '', detectedModelPreview: '', detectedColourPreview: '', plateRedetectionRequested: false, modelRescanRequested: false, colourRedetectionRequested: false, geranScanned: false, scanMessage: '', snackbar: '',
                    norm(value) { return (value || '').trim().toUpperCase(); },
                    get revalidationMode() { return this.plateRedetectionRequested ? 'plate' : (this.modelRescanRequested ? 'model' : (this.colourRedetectionRequested ? 'colour' : null)); },
                    requestRevalidation(type) {
                        if (this.revalidationMode && this.revalidationMode !== type) return;
                        if (type === 'plate') { this.plateRedetectionRequested = true; this.fields.plate_number = this.original.plate_number; }
                        if (type === 'model') { this.modelRescanRequested = true; this.fields.model = this.original.model; }
                        if (type === 'colour') { this.colourRedetectionRequested = true; this.fields.colour = this.original.colour; }
                        this.$nextTick(() => this.$refs.revalidationSection?.scrollIntoView({ behavior: 'smooth', block: 'start' }));
                    },
                    cancelRevalidation() {
                        Object.values(this.previews).forEach(url => URL.revokeObjectURL(url));
                        this.previews = {}; this.validated = {}; this.photoResults = {}; this.detectedPlatePreview = ''; this.detectedModelPreview = ''; this.detectedColourPreview = ''; this.geranScanned = false; this.scanMessage = '';
                        this.plateRedetectionRequested = false; this.modelRescanRequested = false; this.colourRedetectionRequested = false;
                        this.fields.plate_number = this.original.plate_number; this.fields.model = this.original.model; this.fields.colour = this.original.colour;
                        ['front_image','rear_image','side_image','vehicle_geran'].forEach(name => { if (this.$refs[name]) this.$refs[name].value = ''; });
                        ['front_image','rear_image','side_image'].forEach(name => { if (this.$root.elements[name + '_validation_token']) this.$root.elements[name + '_validation_token'].value = ''; });
                        ['registered_owner_name','owner_identity_no','manufacturer','model_name','geran_plate_number'].forEach(name => { if (this.$refs[name]) this.$refs[name].value = ''; });
                    },
                    get plateChanged() { return this.plateRedetectionRequested || this.norm(this.fields.plate_number) !== this.norm(this.original.plate_number); },
                    get modelChanged() { return this.modelRescanRequested || this.norm(this.fields.model) !== this.norm(this.original.model); },
                    get colourChanged() { return this.norm(this.fields.colour) !== this.norm(this.original.colour); },
                    get photosRequired() { return this.plateChanged || this.colourRedetectionRequested || this.colourChanged; },
                    get geranRequired() { return this.plateChanged || this.modelChanged; },
                    get identityChanged() { return this.photosRequired || this.geranRequired; },
                    get evidenceBusy() { return Object.values(this.busy).some(Boolean); },
                    clearEvidenceAfterError(message) {
                        Object.values(this.previews).forEach(url => URL.revokeObjectURL(url));
                        this.previews = {}; this.validated = {}; this.photoResults = {}; this.detectedPlatePreview = ''; this.detectedModelPreview = ''; this.detectedColourPreview = ''; this.geranScanned = false;
                        this.fields.plate_number = this.original.plate_number; this.fields.model = this.original.model; this.fields.colour = this.original.colour;
                        ['front_image','rear_image','side_image','vehicle_geran'].forEach(name => { if (this.$refs[name]) this.$refs[name].value = ''; });
                        ['front_image','rear_image','side_image'].forEach(name => { if (this.$root.elements[name + '_validation_token']) this.$root.elements[name + '_validation_token'].value = ''; });
                        ['registered_owner_name','owner_identity_no','manufacturer','model_name','geran_plate_number'].forEach(name => { if (this.$refs[name]) this.$refs[name].value = ''; });
                        this.scanMessage = ''; this.snackbar = message;
                    },
                    selectEvidence(name, file) { if (!file) return; if (this.previews[name]) URL.revokeObjectURL(this.previews[name]); this.previews[name] = URL.createObjectURL(file); if (name === 'vehicle_geran') { this.geranScanned = false; this.scanMessage = 'Scan this newly selected document before saving.'; } else { this.validated[name] = false; delete this.photoResults[name]; this.$root.elements[name + '_validation_token'].value = ''; const preview=new Image();preview.onload=()=>{if(preview.naturalWidth<800||preview.naturalHeight<450)this.snackbar=`${name.replace('_image','').replace(/^./,c=>c.toUpperCase())} photo is ${preview.naturalWidth} × ${preview.naturalHeight} px. Upload an image of at least 800 × 450 px.`};preview.src=this.previews[name]; } },
                    canonicalPlate(value){return (value||'').toUpperCase().replace(/[^A-Z0-9]/g,'');},
                    applyDetectedColour(){const results=Object.values(this.photoResults).filter(result=>result.detectedColour);if(results.length!==3)return null;const groups={};results.forEach(result=>{const group=result.colourGroup||result.detectedColour;groups[group]=(groups[group]||0)+Number(result.confidence||0)});const winningGroup=Object.entries(groups).sort((a,b)=>b[1]-a[1])[0]?.[0];const best=results.filter(result=>(result.colourGroup||result.detectedColour)===winningGroup).sort((a,b)=>Number(b.confidence||0)-Number(a.confidence||0))[0];if(!best)return null;if(this.revalidationMode==='plate'&&this.norm(best.detectedColour)!==this.norm(this.original.colour))return `Detected colour ${best.detectedColour} does not match this vehicle (${this.original.colour}). Upload photos of the registered vehicle.`;if(this.revalidationMode==='colour'){this.detectedColourPreview=best.detectedColour;this.fields.colour=best.detectedColour;}return null;},
                    async validatePhoto(name, view) { const file=this.$refs[name]?.files[0];if(!file||this.evidenceBusy)return;this.busy[name]=true;const body=new FormData();body.append('image',file);body.append('expected_view',view);try{const response=await fetch('{{ route('driver.vehicles.images.validate') }}',{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body});const data=await response.json();if(!response.ok||!data.accepted)throw new Error(Object.values(data.errors||{})[0]?.[0]||data.message||'Photo validation failed.');if(this.plateRedetectionRequested&&!data.plate_number)throw new Error(`Inappropriate image. Please upload a clear ${view.toLowerCase()} car image with a readable plate number.`);if(this.revalidationMode==='colour'&&!data.detected_colour)throw new Error(`Inappropriate image. Please upload a clear ${view.toLowerCase()} car image with the vehicle colour visible.`);const detectedPlate=this.canonicalPlate(data.plate_number);const expectedPlate=this.canonicalPlate(this.original.plate_number);if(detectedPlate&&!this.plateRedetectionRequested&&detectedPlate!==expectedPlate)throw new Error(`Detected plate ${data.plate_number} does not match this vehicle (${this.original.plate_number}). Upload a photo of the registered vehicle.`);const otherPlates=Object.values(this.photoResults).map(result=>this.canonicalPlate(result.plateNumber)).filter(Boolean);if(detectedPlate&&otherPlates.some(plate=>plate!==detectedPlate))throw new Error('The uploaded vehicle photos contain different plate numbers. Upload photos of the same vehicle.');if(this.plateRedetectionRequested&&detectedPlate&&this.detectedPlatePreview&&detectedPlate!==this.canonicalPlate(this.detectedPlatePreview))throw new Error('The detected plate does not match the plate shown by the other evidence.');this.validated[name]=true;this.photoResults[name]={detectedColour:data.detected_colour,colourGroup:data.colour_group||data.detected_colour,confidence:data.colour_confidence,plateNumber:data.plate_number};this.$root.elements[name+'_validation_token'].value=data.token||'';if(this.plateRedetectionRequested&&data.plate_number)this.detectedPlatePreview=data.plate_number;const colourError=this.applyDetectedColour();if(colourError)throw new Error(colourError);}catch(error){this.clearEvidenceAfterError(error.message);}finally{this.busy[name]=false;} },
                    dateValue(value){const match=(value||'').match(/^(\d{2})[\/.\-](\d{2})[\/.\-](\d{4})$/);return match?`${match[3]}-${match[2]}-${match[1]}`:value;},
                    async scanGeran() { const file=this.$refs.vehicle_geran?.files[0];if(!file||this.evidenceBusy)return;this.busy.vehicle_geran=true;this.scanMessage='Scanning document…';const body=new FormData();body.append('document',file);body.append('expected_document_type','VEHICLE_GERAN');try{const response=await fetch('{{ route('driver.vehicles.documents.ocr') }}',{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body});const data=await response.json();if(!response.ok)throw new Error(data.message||'Unable to scan the Geran.');const extracted=data.fields||{};const set=(ref,key)=>{const value=extracted[key]?.value;if(value!==undefined&&value!==null)this.$refs[ref].value=value};set('registered_owner_name','registered_owner_name');set('owner_identity_no','owner_identity_no');set('manufacturer','manufacturer');set('model_name','model_name');set('geran_plate_number','registration_no');const geranPlate=this.$refs.geran_plate_number.value;const missingRequired=!this.$refs.registered_owner_name.value||!this.$refs.owner_identity_no.value||!this.$refs.manufacturer.value||!this.$refs.model_name.value||!geranPlate;if(missingRequired)throw new Error('Inappropriate image. Please upload a clear Vehicle Geran / VOC image with the required details visible.');if(this.norm(this.$refs.manufacturer.value)!==this.norm(this.original.brand))throw new Error(`The Geran manufacturer (${this.$refs.manufacturer.value||'not detected'}) does not match this vehicle (${this.original.brand}).`);if(!this.plateRedetectionRequested&&this.canonicalPlate(geranPlate)!==this.canonicalPlate(this.original.plate_number))throw new Error(`The Geran plate (${geranPlate}) does not match this vehicle (${this.original.plate_number}).`);if(this.revalidationMode==='model'){this.detectedModelPreview=this.$refs.model_name.value;this.fields.model=this.detectedModelPreview;}if(this.revalidationMode==='plate'&&this.norm(this.$refs.model_name.value)!==this.norm(this.original.model))throw new Error(`The Geran model (${this.$refs.model_name.value}) does not match this vehicle (${this.original.model}).`);if(this.plateRedetectionRequested){if(this.detectedPlatePreview&&this.canonicalPlate(geranPlate)!==this.canonicalPlate(this.detectedPlatePreview))throw new Error(`The Geran plate (${geranPlate}) does not match the plate detected from the vehicle photos (${this.detectedPlatePreview}).`);this.detectedPlatePreview=geranPlate;}this.geranScanned=true;this.scanMessage='Scan complete. Required Geran details were extracted.';}catch(error){this.clearEvidenceAfterError(error.message);}finally{this.busy.vehicle_geran=false;} },
                    evidenceReady(){const photosReady=!this.photosRequired||(['front_image','rear_image','side_image'].every(name=>this.validated[name])&&Object.values(this.photoResults).some(result=>this.canonicalPlate(result.plateNumber)));const geranReady=!this.geranRequired||this.geranScanned;return photosReady&&geranReady;},
                    submitForm(event){if(!this.evidenceReady()){event.preventDefault();const photosValidated=['front_image','rear_image','side_image'].every(name=>this.validated[name]);if(this.photosRequired&&photosValidated&&!Object.values(this.photoResults).some(result=>this.canonicalPlate(result.plateNumber))){this.snackbar='At least one uploaded vehicle photo must show a readable plate number.';}else{this.snackbar=this.photosRequired&&this.geranRequired?'Validate all three vehicle photos and scan the Vehicle Geran/VOC before saving.':(this.photosRequired?'Validate the front, rear, and side vehicle photos before saving.':'Scan the Vehicle Geran/VOC before saving.');}return}this.submitting=true;}
                }" @submit="submitForm($event)">
                    @csrf
                    @method('PUT')
                    @include('driver.vehicles._form', ['vehicle' => $vehicle])

                    <div x-cloak x-show="showPhotoExamples" x-transition.opacity class="fixed inset-0 z-[100] flex items-center justify-center bg-gray-950/70 p-4" @keydown.escape.window="showPhotoExamples=false">
                        <div class="w-full max-w-4xl overflow-hidden rounded-2xl bg-white shadow-2xl" @click.outside="showPhotoExamples=false">
                            <div class="flex items-start justify-between border-b border-gray-100 px-5 py-4"><div><h2 class="font-bold text-gray-950">Vehicle photo examples</h2><p class="mt-1 text-xs text-gray-500">Keep the whole vehicle visible and photograph each requested angle clearly.</p></div><button type="button" @click="showPhotoExamples=false" class="rounded-lg p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-700" aria-label="Close photo examples"><x-icons.lucide name="x" class="h-5 w-5" /></button></div>
                            <div class="grid max-h-[75vh] gap-4 overflow-auto bg-gray-100 p-4 sm:grid-cols-3 sm:p-6">@foreach([['Front','front-example.png'],['Rear','rear-example.png'],['Side','side-example.png']] as [$exampleLabel,$exampleFile])<figure class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><img src="{{ asset('images/vehicle-photo-examples/'.$exampleFile) }}" alt="Correct {{ strtolower($exampleLabel) }} vehicle photo example" class="aspect-video w-full object-cover"><figcaption class="border-t border-gray-200 px-3 py-2 text-center text-sm font-semibold text-gray-700">{{ $exampleLabel }} view</figcaption></figure>@endforeach</div>
                        </div>
                    </div>

                    <div x-cloak x-show="showGeranExample" x-transition.opacity class="fixed inset-0 z-[100] flex items-center justify-center bg-gray-950/70 p-4" @keydown.escape.window="showGeranExample=false">
                        <div class="w-full max-w-3xl overflow-hidden rounded-2xl bg-white shadow-2xl" @click.outside="showGeranExample=false"><div class="flex items-start justify-between border-b border-gray-100 px-5 py-4"><div><h2 class="font-bold text-gray-950">Vehicle Geran photo example</h2><p class="mt-1 text-xs text-gray-500">Reference only — your document details and layout may differ.</p></div><button type="button" @click="showGeranExample=false" class="rounded-lg p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-700" aria-label="Close Geran example"><x-icons.lucide name="x" class="h-5 w-5" /></button></div><div class="max-h-[75vh] overflow-auto bg-gray-100 p-4 sm:p-6"><img src="{{ asset('images/vehicle-photo-examples/geran-example.png') }}" alt="Example showing how to photograph a Vehicle Geran with all four corners visible" class="mx-auto max-h-[68vh] rounded-lg border border-gray-200 bg-white object-contain shadow-sm"></div></div>
                    </div>

                    <div class="mt-8 flex flex-col-reverse gap-3 border-t border-gray-100 pt-6 sm:flex-row sm:justify-end">
                        <a href="{{ route('driver.vehicles.show', $vehicle) }}" class="inline-flex min-h-[44px] items-center justify-center rounded-xl border border-gray-300 px-5 py-2.5 text-sm font-semibold text-gray-700 hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2E7D32]">
                            Cancel
                        </a>
                        <button type="submit" :disabled="submitting" class="inline-flex min-h-[44px] items-center justify-center rounded-xl bg-[#2E7D32] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#256b29] disabled:cursor-wait disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2E7D32] focus-visible:ring-offset-2">
                            <span x-show="!submitting">Save changes</span>
                            <span x-cloak x-show="submitting">Saving changes…</span>
                        </button>
                    </div>
                    <div x-cloak x-show="snackbar" x-transition class="fixed bottom-5 right-6 z-50 flex max-w-md items-start gap-3 rounded-xl bg-gray-950 px-4 py-3 text-sm text-white shadow-2xl" role="alert"><span class="font-bold text-red-400">!</span><p x-text="snackbar" class="flex-1"></p><button type="button" @click="snackbar=''">×</button></div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>
